/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Draw: typeof import('./src/components/draw.vue')['default']
    Drew: typeof import('./src/components/drew.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
